### PR TITLE
Fix: New Logo Proposal

### LINKED ISSUE #18: Logo/banner logo still look weak
I am not married to the logo at all, but something that conveys "database" (cylinder) + "direction" (up arrow) + ".NET" (blue/purple) is what I was going for. It's not bad for a ChatGPT generated icon, but it could certainly be better:

The banner...

...doesn't look great in dark mode:

image

So, if you want to contribute a logo you may as well create a better banner while you're at it. Any other bits of design, I am more than happy to take suggestions / PR / critiques!

### PR DESCRIPTION
**Pull request by michaelmuthomi**
Hope this logo meets the criteria you are looking for.
fixes #18

### CODE REVIEW

**Comment by mgroves** [comment]
That is great! Can you isolate just the icon part, so I can use that with NuGet? https://www.nuget.org/packages/NoSqlMigrator

**Comment by michaelmuthomi** [comment]
I have isolated The icon by liking using 
```
<p align="center">
    <img src="Logo/nosqlmigrator.png" alt="Logo">
</p>
```

**Comment by mgroves** [comment]
But I mean, just the icon without the text, like this file: https://github.com/mgroves/NoSqlMigrator/blob/main/NoSqlMigrator/logo.png

**Comment by michaelmuthomi** [comment]
Should i switch the logo in the readme to just the icon or i should leave it as is and just include the icon the Logo folder.

**Comment by michaelmuthomi** [comment]
@mgroves It's been some time since we last connected. I wanted to take a moment to check in and inquire about your thoughts on the logo.

**Comment by mgroves** [comment]
Sorry, I've been traveling and then sick. I appreciate your work, and I want to give it the time that it deserves. It's definitely still on my mind, and I will get to it as soon as I can. Thank you!

**Comment by michaelmuthomi** [comment]
No worries! I understand that things come up. Take your time and get better soon.

**Comment by mgroves** [comment]
The logo.png looks good, but it seems like there's a lot of padding around it, and it's also not a square aspect ratio.

You can see how this will be used for the NuGet package here: https://www.nuget.org/packages/NoSqlMigrator

image

**Comment by mgroves** [comment]
That looks great. GitHub is saying it's 128x126, is that accurate? If so, can you just add a couple blank lines to the height so it's exactly square?

**Comment by michaelmuthomi** [comment]
> That looks great. GitHub is saying it's 128x126, is that accurate? If so, can you just add a couple blank lines to the height so it's exactly square?

@mgroves It was a minor error but now the aspect ratio is proportional, 128x128

**Comment by mgroves** [comment]
It looks incredible, thank you for your work! I'll add this to the docs the next time I work on it, and I'll add it the next time I deploy to NuGet, and I'll even see if I can add it to the executable :)

**Pull request merged**
